name: Python CI
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set Up Python ${{matrix.node-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: python './1. The Money Problem/test_money.py'
        shell: bash
      